#!/bin/sh
set -e -x

# Installing tools
apk add --no-cache \
  curl=${CURL_VERSION} \
  jq=${JQ_VERSION} \
  coreutils=${COREUTILS_VERSION}

# Add esex group
addgroup -S esex

# Add esex user
adduser \
  -s /bin/sh \
  -G esex \
  -D esex

# Adding entrypoint
mv /resources/entrypoint.sh /entrypoint.sh
